# Generated by scripts/sync-package-manifests.mjs
cask "deco" do
  version "0.8.0"
  sha256 "d53367ff2b0406f492298e0b82c721ac7e65fd3c44f138f75b3331d67dbb7dc9"

  url "https://github.com/Dendro-X0/Deco/releases/download/v0.8.0/Deco_0.8.0_aarch64.dmg"
  name "Deco"
  desc "Disk cleanup for developer machines"
  homepage "https://github.com/Dendro-X0/Deco"

  depends_on macos: ">= :monterey"
  depends_on arch: :arm64

  app "Deco.app"

  zap trash: [
    "~/Library/Application Support/com.dendrox.deco",
  ]
end
