# Generated by scripts/sync-package-manifests.mjs
cask "deco" do
  version "0.9.11"
  sha256 "16b576981185613945c709e9fa1d540fc6604ce0270e96e13e6acc0ef47bf06b"

  url "https://github.com/Dendro-X0/Deco/releases/download/v0.9.11/Deco_0.9.11_aarch64.dmg"
  name "Deco"
  desc "Disk cleanup for developer machines"
  homepage "https://github.com/Dendro-X0/Deco"

  depends_on macos: ">= :monterey"
  depends_on arch: :arm64

  app "Deco.app"

  zap trash: [
    "~/Library/Application Support/com.dendrox.deco",
  ]
end
